parameters:
  out_len:
    value: 4
  patch_dim:
    value: 6
  emb_dim:
    value: 256
  n_agg:
    value: 5
  factor:
    value: 10
  d_model:
    value: 128
  d_ff:
    value: 1024
  n_heads:
    value: 4
  e_layers:
    value: 3
  d_layers:
    value: 1
  dropout:
    value: 0.1
  learning_rate:
    value: 0.0000923245840094706
  seed:
    value: 3290
  data:
    value: 'bank'
